import type { Tokens } from '../tokens/types.ts'
import { resolveSemantic } from '../utils/resolve.ts'

const HEADER =
  '/* generated by `ds generate` — do not edit; edit design-system/tokens.ts instead. */'

export function generateGlobalsCss(tokens: Tokens): string {
  const lines: string[] = [HEADER, '']

  lines.push('@theme inline {')

  for (const semanticName of Object.keys(tokens.semanticColors)) {
    lines.push(`  --color-${semanticName}: var(--${semanticName});`)
  }
  lines.push('')

  // fonts (data-driven from tokens.fontFamilies)
  for (const key of Object.keys(tokens.fontFamilies)) {
    lines.push(`  --font-${key}: var(--font-${key});`)
  }
  lines.push('')

  for (const [key, value] of Object.entries(tokens.borderRadius)) {
    const cssKey = key === 'DEFAULT' ? '' : `-${key}`
    lines.push(`  --radius${cssKey}: ${value};`)
  }
  lines.push('')

  for (const [key, value] of Object.entries(tokens.durations)) {
    lines.push(`  --duration-${key}: ${value}ms;`)
  }
  lines.push('')

  for (const [key, value] of Object.entries(tokens.easings)) {
    lines.push(`  --ease-${key}: ${value};`)
  }
  lines.push('')

  for (const [key, entry] of Object.entries(tokens.fontSizes)) {
    lines.push(`  --text-${key}: ${entry.size}px;`)
    lines.push(`  --text-${key}--line-height: ${entry.leading}px;`)
  }
  lines.push('')

  // spacing scale (Tailwind 4 reads --spacing-N for p-N, m-N, etc.)
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`  --spacing-${key}: ${value};`)
  }

  lines.push('}')
  lines.push('')

  // :root — actual oklch values per semantic
  lines.push(':root {')
  for (const semanticName of Object.keys(tokens.semanticColors)) {
    const resolved = resolveSemantic(semanticName, tokens)
    lines.push(`  --${semanticName}: ${resolved.oklch};`)
  }
  lines.push('}')

  return lines.join('\n')
}
