import type { Tokens } from '../tokens/types.ts'
import { resolveSemantic } from '../utils/resolve.ts'

const HEADER = '// generated by `ds generate` — do not edit; edit design-system/tokens.ts instead.'

export function generateTailwindJs(tokens: Tokens): string {
  const lines: string[] = [HEADER, '']

  lines.push('colors: {')
  for (const semanticName of Object.keys(tokens.semanticColors)) {
    const resolved = resolveSemantic(semanticName, tokens)
    const value = resolved.rgba ?? resolved.hex
    lines.push(`  '${semanticName}': '${value}',`)
  }
  lines.push('},')

  lines.push('fontFamily: {')
  for (const [key, entry] of Object.entries(tokens.fontFamilies)) {
    lines.push(`  '${key}': ['${entry.fontName}'],`)
  }
  lines.push('},')

  lines.push('borderRadius: {')
  for (const [key, value] of Object.entries(tokens.borderRadius)) {
    lines.push(`  '${key}': '${value}',`)
  }
  lines.push('},')

  lines.push('fontSize: {')
  for (const [key, entry] of Object.entries(tokens.fontSizes)) {
    lines.push(`  '${key}': ['${entry.size}px', '${entry.leading}px'],`)
  }
  lines.push('},')

  return lines.join('\n')
}
