import type { Tokens } from '../tokens/types.ts'
import { resolveOverlay, resolvePrimitive, resolveSemantic } from '../utils/resolve.ts'

const HEADER =
  '// generated by `ds generate` — do not edit; edit design-system/tokens.ts instead.'

function camel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

export function generateThemeTs(tokens: Tokens): string {
  const lines: string[] = [HEADER, '']

  lines.push('export const colors = {')
  for (const semanticName of Object.keys(tokens.semanticColors)) {
    const resolved = resolveSemantic(semanticName, tokens)
    const value = resolved.rgba ?? resolved.hex
    lines.push(`  ${camel(semanticName)}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  const overlays = tokens.overlays ?? {}
  if (Object.keys(overlays).length > 0) {
    lines.push('export const overlays = {')
    for (const overlayName of Object.keys(overlays)) {
      const resolved = resolveOverlay(overlayName, tokens)
      lines.push(`  ${overlayName}: '${resolved.rgba}',`)
    }
    lines.push('} as const')
    lines.push('')
  }

  lines.push('export const durations = {')
  for (const [key, value] of Object.entries(tokens.durations)) {
    lines.push(`  ${camel(key)}: ${value},`)
  }
  lines.push('} as const')
  lines.push('')

  lines.push('export const easings = {')
  for (const [key, value] of Object.entries(tokens.easings)) {
    lines.push(`  ${camel(key)}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  const springs = tokens.springs ?? {}
  if (Object.keys(springs).length > 0) {
    lines.push('export const springs = {')
    for (const [key, cfg] of Object.entries(springs)) {
      lines.push(
        `  ${camel(key)}: { damping: ${cfg.damping}, stiffness: ${cfg.stiffness} },`,
      )
    }
    lines.push('} as const')
    lines.push('')
  }

  const shadows = tokens.shadows ?? {}
  const fr = shadows['focusRing']
  if (fr) {
    const frPrimitive = resolvePrimitive(fr.shadowColorAlias, tokens)
    lines.push('export const focusRing = {')
    lines.push(`  shadowColor: '${frPrimitive.hex}',`)
    lines.push(`  shadowOpacity: ${fr.shadowOpacity},`)
    lines.push(`  shadowRadius: ${fr.shadowRadius},`)
    lines.push(
      `  shadowOffset: { width: ${fr.shadowOffsetWidth}, height: ${fr.shadowOffsetHeight} },`,
    )
    lines.push(`  borderRadius: 4,`)
    lines.push('} as const')
    lines.push('')
  }

  const otherShadows = Object.entries(shadows).filter(([k]) => k !== 'focusRing')
  if (otherShadows.length > 0) {
    lines.push('export const shadows = {')
    for (const [key, cfg] of otherShadows) {
      const primitive = resolvePrimitive(cfg.shadowColorAlias, tokens)
      lines.push(`  ${camel(key)}: {`)
      lines.push(`    shadowColor: '${primitive.hex}',`)
      lines.push(`    shadowOpacity: ${cfg.shadowOpacity},`)
      lines.push(`    shadowRadius: ${cfg.shadowRadius},`)
      lines.push(
        `    shadowOffset: { width: ${cfg.shadowOffsetWidth}, height: ${cfg.shadowOffsetHeight} },`,
      )
      lines.push(`  },`)
    }
    lines.push('} as const')
    lines.push('')
  }

  const iconSizes = tokens.iconSizes ?? {}
  if (Object.keys(iconSizes).length > 0) {
    lines.push('export const iconSizes = {')
    for (const [key, value] of Object.entries(iconSizes)) {
      lines.push(`  ${key}: ${value},`)
    }
    lines.push('} as const')
  }

  return lines.join('\n')
}
